# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94aae380db4f769550b92aa84684a486773ea3a6a09fa46633aec8fd0c6d537558e1cde042b514d65efa2bb0763bd50534639e8735147a1540e495f1248e04b8

test:
  secret_key_base: 30bf543bb773f1680be7cae5a9dc2fc1700dea1ca2b41870d4c50d14326be10f09b4816b26996fff1a40a19169a588725ee78b8ee32b5e01e24dc9a7fbe95e52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
